#ifndef CONSTANTS_H
# define CONTANTS_H

/* FORMATS CONSTANTS */
#define DECIMAL_FORMAT 'd'
#define CHARACTER_FORMAT 'c'
#define INTEGER_FORMAT 'i'
#define STRING_FORMAT 's'
#define POINTER_FORMAT 'p'
#define UNSIGNED_DECIMAL_FORMAT 'u'
#define HEX_LOWER_FORMAT 'x'
#define HEX_UPPER_FORMAT 'X'
#define PERCENTAGE_FORMAT '%'
#define BACKSLAH '\\'

/* BASE CONTANTS */
#define DECIMAL_BASE_NUMBER 10
#define HEXADECIMAL_BASE_NUMBER 16
#define UPPER_HEX_BASE_CONTENT "0123456789ABCDEF"
#define LOWER_HEX_BASE_CONTENT "0123456789abcdef"

#endif